source 'https://rubygems.org'

gem 'rspec', '~> 3.12'
gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'
gem 'database_cleaner', '~> 2.0'
gem 'faker', '~> 3.2'
gem 'pry', '~> 0.14'
gem 'rack-test', '~> 2.1'
gem 'webmock', '~> 3.18'
gem 'vcr', '~> 6.1'

group :test do
  gem 'rspec-json_expectations', '~> 2.2'
end
